# Generated by Django 4.2.5 on 2025-04-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_author_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='customer_review_rank',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
